module.exports = [
  { name: "Afganistan", code: "af", aliases: ["Afghanistan"] },
  { name: "Arnavutluk", code: "al", aliases: ["Albania"] },
  { name: "Cezayir", code: "dz", aliases: ["Algeria"] },
  { name: "Andorra", code: "ad", aliases: ["Andorra"] },
  { name: "Angola", code: "ao", aliases: ["Angola"] },
  { name: "Antigua ve Barbuda", code: "ag", aliases: ["Antigua and Barbuda"] },
  { name: "Arjantin", code: "ar", aliases: ["Argentina"] },
  { name: "Ermenistan", code: "am", aliases: ["Armenia"] },
  { name: "Avustralya", code: "au", aliases: ["Australia"] },
  { name: "Avusturya", code: "at", aliases: ["Austria"] },
  { name: "Azerbaycan", code: "az", aliases: ["Azerbaijan"] },

  { name: "Bahamalar", code: "bs", aliases: ["Bahamas"] },
  { name: "Bahreyn", code: "bh", aliases: ["Bahrain"] },
  { name: "Bangladeş", code: "bd", aliases: ["Bangladesh"] },
  { name: "Barbados", code: "bb", aliases: ["Barbados"] },
  { name: "Belarus", code: "by", aliases: ["Belarus"] },
  { name: "Belçika", code: "be", aliases: ["Belgium"] },
  { name: "Belize", code: "bz", aliases: ["Belize"] },
  { name: "Benin", code: "bj", aliases: ["Benin"] },
  { name: "Bhutan", code: "bt", aliases: ["Bhutan"] },
  { name: "Bolivya", code: "bo", aliases: ["Bolivia"] },
  { name: "Bosna-Hersek", code: "ba", aliases: ["Bosnia and Herzegovina"] },
  { name: "Botsvana", code: "bw", aliases: ["Botswana"] },
  { name: "Brezilya", code: "br", aliases: ["Brazil"] },
  { name: "Brunei", code: "bn", aliases: ["Brunei"] },
  { name: "Bulgaristan", code: "bg", aliases: ["Bulgaria"] },
  { name: "Burkina Faso", code: "bf", aliases: ["Burkina Faso"] },
  { name: "Burundi", code: "bi", aliases: ["Burundi"] },

  { name: "Kamboçya", code: "kh", aliases: ["Cambodia"] },
  { name: "Kamerun", code: "cm", aliases: ["Cameroon"] },
  { name: "Kanada", code: "ca", aliases: ["Canada"] },
  { name: "Yeşil Burun Adaları", code: "cv", aliases: ["Cape Verde"] },
  { name: "Orta Afrika Cumhuriyeti", code: "cf", aliases: ["Central African Republic"] },
  { name: "Çad", code: "td", aliases: ["Chad"] },
  { name: "Şili", code: "cl", aliases: ["Chile"] },
  { name: "Çin", code: "cn", aliases: ["China"] },
  { name: "Kolombiya", code: "co", aliases: ["Colombia"] },
  { name: "Komorlar", code: "km", aliases: ["Comoros"] },
  { name: "Kongo", code: "cg", aliases: ["Republic of the Congo"] },
  { name: "Kosta Rika", code: "cr", aliases: ["Costa Rica"] },
  { name: "Hırvatistan", code: "hr", aliases: ["Croatia"] },
  { name: "Küba", code: "cu", aliases: ["Cuba"] },
  { name: "Kıbrıs", code: "cy", aliases: ["Cyprus"] },
  { name: "Çekya", code: "cz", aliases: ["Czech Republic", "Czechia"] },

  { name: "Danimarka", code: "dk", aliases: ["Denmark"] },
  { name: "Cibuti", code: "dj", aliases: ["Djibouti"] },
  { name: "Dominika", code: "dm", aliases: ["Dominica"] },
  { name: "Dominik Cumhuriyeti", code: "do", aliases: ["Dominican Republic"] },

  { name: "Ekvador", code: "ec", aliases: ["Ecuador"] },
  { name: "Mısır", code: "eg", aliases: ["Egypt"] },
  { name: "El Salvador", code: "sv", aliases: ["El Salvador"] },
  { name: "Ekvator Ginesi", code: "gq", aliases: ["Equatorial Guinea"] },
  { name: "Eritre", code: "er", aliases: ["Eritrea"] },
  { name: "Estonya", code: "ee", aliases: ["Estonia"] },
  { name: "Etiyopya", code: "et", aliases: ["Ethiopia"] },

  { name: "Fiji", code: "fj", aliases: ["Fiji"] },
  { name: "Finlandiya", code: "fi", aliases: ["Finland"] },
  { name: "Fransa", code: "fr", aliases: ["France"] },

  { name: "Gabon", code: "ga", aliases: ["Gabon"] },
  { name: "Gambiya", code: "gm", aliases: ["Gambia"] },
  { name: "Gürcistan", code: "ge", aliases: ["Georgia"] },
  { name: "Almanya", code: "de", aliases: ["Germany"] },
  { name: "Gana", code: "gh", aliases: ["Ghana"] },
  { name: "Yunanistan", code: "gr", aliases: ["Greece"] },
  { name: "Guatemala", code: "gt", aliases: ["Guatemala"] },
  { name: "Gine", code: "gn", aliases: ["Guinea"] },
  { name: "Gine-Bissau", code: "gw", aliases: ["Guinea-Bissau"] },
  { name: "Guyana", code: "gy", aliases: ["Guyana"] },

  { name: "Haiti", code: "ht", aliases: ["Haiti"] },
  { name: "Honduras", code: "hn", aliases: ["Honduras"] },
  { name: "Macaristan", code: "hu", aliases: ["Hungary"] },

  { name: "İzlanda", code: "is", aliases: ["Iceland"] },
  { name: "Hindistan", code: "in", aliases: ["India"] },
  { name: "Endonezya", code: "id", aliases: ["Indonesia"] },
  { name: "İran", code: "ir", aliases: ["Iran"] },
  { name: "Irak", code: "iq", aliases: ["Iraq"] },
  { name: "İrlanda", code: "ie", aliases: ["Ireland"] },
  { name: "İsrail", code: "il", aliases: ["Israel"] },
  { name: "İtalya", code: "it", aliases: ["Italy"] },

  { name: "Jamaika", code: "jm", aliases: ["Jamaica"] },
  { name: "Japonya", code: "jp", aliases: ["Japan"] },
  { name: "Ürdün", code: "jo", aliases: ["Jordan"] },

  { name: "Kazakistan", code: "kz", aliases: ["Kazakhstan"] },
  { name: "Kenya", code: "ke", aliases: ["Kenya"] },
  { name: "Kuveyt", code: "kw", aliases: ["Kuwait"] },
  { name: "Kırgızistan", code: "kg", aliases: ["Kyrgyzstan"] },

  { name: "Laos", code: "la", aliases: ["Laos"] },
  { name: "Letonya", code: "lv", aliases: ["Latvia"] },
  { name: "Lübnan", code: "lb", aliases: ["Lebanon"] },
  { name: "Lesotho", code: "ls", aliases: ["Lesotho"] },
  { name: "Liberya", code: "lr", aliases: ["Liberia"] },
  { name: "Libya", code: "ly", aliases: ["Libya"] },
  { name: "Lihtenştayn", code: "li", aliases: ["Liechtenstein"] },
  { name: "Litvanya", code: "lt", aliases: ["Lithuania"] },
  { name: "Lüksemburg", code: "lu", aliases: ["Luxembourg"] },

  { name: "Madagaskar", code: "mg", aliases: ["Madagascar"] },
  { name: "Malavi", code: "mw", aliases: ["Malawi"] },
  { name: "Malezya", code: "my", aliases: ["Malaysia"] },
  { name: "Maldivler", code: "mv", aliases: ["Maldives"] },
  { name: "Mali", code: "ml", aliases: ["Mali"] },
  { name: "Malta", code: "mt", aliases: ["Malta"] },
  { name: "Moritanya", code: "mr", aliases: ["Mauritania"] },
  { name: "Mauritius", code: "mu", aliases: ["Mauritius"] },
  { name: "Meksika", code: "mx", aliases: ["Mexico"] },
  { name: "Moldova", code: "md", aliases: ["Moldova"] },
  { name: "Monako", code: "mc", aliases: ["Monaco"] },
  { name: "Moğolistan", code: "mn", aliases: ["Mongolia"] },
  { name: "Karadağ", code: "me", aliases: ["Montenegro"] },
  { name: "Fas", code: "ma", aliases: ["Morocco"] },
  { name: "Mozambik", code: "mz", aliases: ["Mozambique"] },
  { name: "Myanmar", code: "mm", aliases: ["Myanmar", "Burma"] },

  { name: "Namibya", code: "na", aliases: ["Namibia"] },
  { name: "Nepal", code: "np", aliases: ["Nepal"] },
  { name: "Hollanda", code: "nl", aliases: ["Netherlands"] },
  { name: "Yeni Zelanda", code: "nz", aliases: ["New Zealand"] },
  { name: "Nikaragua", code: "ni", aliases: ["Nicaragua"] },
  { name: "Nijer", code: "ne", aliases: ["Niger"] },
  { name: "Nijerya", code: "ng", aliases: ["Nigeria"] },
  { name: "Kuzey Makedonya", code: "mk", aliases: ["North Macedonia"] },
  { name: "Norveç", code: "no", aliases: ["Norway"] },

  { name: "Umman", code: "om", aliases: ["Oman"] },

  { name: "Pakistan", code: "pk", aliases: ["Pakistan"] },
  { name: "Panama", code: "pa", aliases: ["Panama"] },
  { name: "Papua Yeni Gine", code: "pg", aliases: ["Papua New Guinea"] },
  { name: "Paraguay", code: "py", aliases: ["Paraguay"] },
  { name: "Peru", code: "pe", aliases: ["Peru"] },
  { name: "Filipinler", code: "ph", aliases: ["Philippines"] },
  { name: "Polonya", code: "pl", aliases: ["Poland"] },
  { name: "Portekiz", code: "pt", aliases: ["Portugal"] },

  { name: "Katar", code: "qa", aliases: ["Qatar"] },

  { name: "Romanya", code: "ro", aliases: ["Romania"] },
  { name: "Rusya", code: "ru", aliases: ["Russia", "Russian Federation"] },
  { name: "Ruanda", code: "rw", aliases: ["Rwanda"] },

  { name: "Suudi Arabistan", code: "sa", aliases: ["Saudi Arabia"] },
  { name: "Senegal", code: "sn", aliases: ["Senegal"] },
  { name: "Sırbistan", code: "rs", aliases: ["Serbia"] },
  { name: "Singapur", code: "sg", aliases: ["Singapore"] },
  { name: "Slovakya", code: "sk", aliases: ["Slovakia"] },
  { name: "Slovenya", code: "si", aliases: ["Slovenia"] },
  { name: "Somali", code: "so", aliases: ["Somalia"] },
  { name: "Güney Afrika", code: "za", aliases: ["South Africa"] },
  { name: "Güney Sudan", code: "ss", aliases: ["South Sudan"] },
  { name: "İspanya", code: "es", aliases: ["Spain"] },
  { name: "Sri Lanka", code: "lk", aliases: ["Sri Lanka"] },
  { name: "Sudan", code: "sd", aliases: ["Sudan"] },
  { name: "Surinam", code: "sr", aliases: ["Suriname"] },
  { name: "İsveç", code: "se", aliases: ["Sweden"] },
  { name: "İsviçre", code: "ch", aliases: ["Switzerland"] },
  { name: "Suriye", code: "sy", aliases: ["Syria"] },

  { name: "Tayland", code: "th", aliases: ["Thailand"] },
  { name: "Togo", code: "tg", aliases: ["Togo"] },
  { name: "Tunus", code: "tn", aliases: ["Tunisia"] },
  { name: "Türkiye", code: "tr", aliases: ["Turkey"] },
  { name: "Türkmenistan", code: "tm", aliases: ["Turkmenistan"] },

  { name: "Uganda", code: "ug", aliases: ["Uganda"] },
  { name: "Ukrayna", code: "ua", aliases: ["Ukraine"] },
  { name: "Birleşik Arap Emirlikleri", code: "ae", aliases: ["United Arab Emirates"] },
  { name: "Birleşik Krallık", code: "gb", aliases: ["United Kingdom", "UK"] },
  { name: "Amerika Birleşik Devletleri", code: "us", aliases: ["United States", "USA"] },
  { name: "Uruguay", code: "uy", aliases: ["Uruguay"] },
  { name: "Özbekistan", code: "uz", aliases: ["Uzbekistan"] },

  { name: "Venezuela", code: "ve", aliases: ["Venezuela"] },
  { name: "Vietnam", code: "vn", aliases: ["Vietnam"] },

  { name: "Yemen", code: "ye", aliases: ["Yemen"] },

  { name: "Zambiya", code: "zm", aliases: ["Zambia"] },
  { name: "Zimbabve", code: "zw", aliases: ["Zimbabwe"] }
];
